# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-cogwheels
  version: "0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django-cogwheels-${{ version }}.tar.gz
  sha256: 848a4d9f2c96c582a4a4f2e7c276dfd95ab3905748cae13bb7c4b365a6717e94

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2

tests:
  - python:
      imports:
        - cogwheels
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: A consistent, user-friendly solution for adding app-specific settings your Django package, reusable app or framework.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/ababic/django-cogwheels/

extra:
  recipe-maintainers:
    - rxm7706
